### ISSUE TITLE
草鞋没号 todo list

### ISSUE THREAD

**Issue by caoxiemeihao** [youngleish/keep-love#18]
#### 2022-07-07

vite-plugin-esmodule

- [x] Automatic identification of ESM packages

electron-vite/*-boilerplate

- [x] Update ESM packages chapter of README

vite-plugin-electron-renderer@0.5.3

- [x] BUG fix

#### 2022-06-29

vite-plugin-electron@0.7.0

- [x] Restart when Vite dev-server reload.
- [ ] ~~Inject path of electorn-main/electron-preload path after build~~ 🤔
- [x] Check main field of package.json
- [x] Provide a `electron-env.d.ts`
